#Mail  configuration
mail:
  username: 'xxxx@163.com'
  password: 'xxxx'
  host:     'smtp.163.com'
  port:     "465"

#Mail to   configuration
mailto:
  mails: "xxxxxxx@163.com"

#Dingding to configuration
dingding:
  webhook: ''

#Weixin to configuration
weixin:
  webhook: ''